server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/Website
    name:
    password:
  sql:
    init:
      mode: always